version: '3.9'

services:
  nextjs-app:
    image: nextjs-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - wiremock
      - mongo
  
  wiremock:
    image: wiremock/wiremock:3.9.2
    ports:
      - "8080:8080"
    networks:
      - app-net
    volumes:
      - ./wiremock:/home/wiremock
    command: --verbose

  mongo:
    image: mongo:noble
    ports:
     - "27017:27017"
    networks:
      - app-net
    volumes:
      - mongo-data:/data/db

networks:
  app-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local